---
- name: Playbook for ec2
  hosts: localhost
  gather_facts: false
  tasks: 
  - name: Create security group
    ec2_group: 
      name: sec_group_ec2
      description: "this is test "
      vpc_id: vpc-2ada9250
      region: "{{ Enter_reghion_here }}"
      rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
    register: result_sec_group

    
  - name: Upload public key to AWS
    ec2: 
      key_name: 
      region: "{{ Enter_reghion_here }}"
      instance_type: "{{ Enter_instance_type_here }}"
      image: ami-0a887e401f7654935      
      count: 1
      wait: yes
      vpc_subnet_id: subnet-c6c7088b
      assign_public_ip: yes
      group: sec_group_ec2
      instance_tags:
        env: test_ect
      count_tag:
        name: somename
    register: ec2_out
    tags: "create_ec2



   #- name: wait for ssh
    # wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
    #wait_items: '{{ec2_out_instance}}'  
    