---

- hosts: localhost
  connection: local
  gather_facts: False
    - name: Create security group
          ec2_group:
            name: sec_group_ec2
            description: "this is test "
            vpc_id: 12345
            region: us-east-1
            rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
              register: result_sec_group

    
    - name: Upload public key to AWS
          ec2_key:
            name: ec2-name
            instance_type: t2.micor
            key_material: "{{ lookup('file', '/Users/root/.ssh/id_rsa.pub') }}"
            region: us-east-1
            image: ami-4bf3d731
            count: 1
            wait: yes
            vpc_subnet_id: subnet-c6c7088b
            register: ec2_out
            assign_public_ip: yes
            group: sec_group_ec2


    - name: wait for ssh
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      wait_items: '{{ec2_out_instance}}'   

         
      


      tags: ['create_ec2']