---
- name: Test Playbook
  hosts: all
  become: true
  become_method: sudo
  connection: ssh
  ignore_errors: false
  tasks:
    - name: block
      block:
        - name: install apache
          package: 
            name: httpd
            state: latest
      rescue: 
        - name: install apache2
          package: 
            name: apache2
            state: latest
          notify: httpd
  handlers: 
    - name: httpd
      systemd: 
        name: httpd
        state: restarted